SCE=-4
CTLE=-3
CE=-2
CS=-1
OK=0
RE=1
TLE=2
MLE=3
AC=4
WA=5
PE=6
PC=7
JF=8
SKIP=9
judgeStatus=["OK","Runtime Error","Time Limit Exceeded","Memory Limit Exceeded","Accepted","Wrong Answer","Presentation Error","Partially Correct","Judgement Failed","Skipped"]
